numberOfDataSources:
  type: static
  count: 2
caseId: increasing
load: 20
type: "load"
loadType: constant
dataSourceTopology:
  dataSources:
    - name: "SensorA"
      sink:
        type: kafkaValidation
        bootstrapServer: "localhost:9092"
        topic: "log7"
        partition:
          type: constant
          number: 0
        validationTopic: "validation2"
        validationSplit: 5
      eventGeneration:
        type: "classic"
        selection: uniform
        from:
          events:
            - duration:
                type: gaussian
                mu: 4
                sigma: 2
              transition:
                type: next_sensor
                index: 1
              activity: "SensorA"
    - name: "SensorB"
      sink:
        type: kafkaValidation
        bootstrapServer: "localhost:9092"
        topic: "log6"
        partition:
          type: constant
          number: 1
        validationTopic: "validation2"
        validationSplit: 5
      eventGeneration:
        type: "classic"
        selection: "genericProbability"
        distribution: [ 0.5, 0.5 ]
        from:
          events:
            - duration:
                type: gaussian
                mu: 4
                sigma: 2
              transition:
                type: next_sensor
                index: 2
              activity: "SensorB-1"
            - duration:
                type: gaussian
                mu: 4
                sigma: 2
              transition:
                type: next_sensor
                index: 2
              activity: "SensorB-2"
    - name: "SensorC"
      sink:
        type: kafkaValidation
        bootstrapServer: "localhost:9092"
        topic: "log6"
        partition:
          type: constant
          number: 2
        validationTopic: "validation2"
        validationSplit: 5
      eventGeneration:
        type: "classic"
        selection: uniform
        from:
          events:
            - duration:
                type: gaussian
                mu: 4
                sigma: 2
              transition:
                type: next_sensor
                index: 3
              activity: "SensorC"