numberOfDataSources:
  type: static
  count: 2
caseId: increasing
eventLoop.loadProfile.maximalLoad: 200
eventLoop:
  type: load
  loadProfile:
    type: gradual
    tickCount: 100
    minimalLoad: 100
dataSourceTopology:
  dataSources:
    - name: "Sensor 0"
      sink:
        type: kafkaValidation
        bootstrapServer: "kube1-1:30376"
        topic: "log"
        partition: 0
        validationTopic: "validation"
        validationSplit: 5
      eventGeneration:
        type: "classic"
        selection: uniform
        from:
          events:
            - duration:
                type: gaussian
                mu: 4
                sigma: 2
              transition:
                type: next_sensor
                index: 1
              activities:
                selection: uniform
                from:
                  type: list
                  values:
                    - [ "Hugo", "Jonas" ]
    - name: "Sensor 1"
      sink:
        type: ui
        #type: kafkaValidation
        #bootstrapServer: "kube1-1:30376"
        #topic: "log"
        #partition: 1
        #validationTopic: "validation"
        #validationSplit: 5
      eventGeneration:
        type: "classic"
        selection: "genericProbability"
        distribution: [0.9, 0.1]
        from:
          events:
            - duration:
                type: static
                duration: 1
              transition:
                type: next_sensor
                index: 1
              activities:
                selection: uniform
                from:
                  type: list
                  values:
                    - [ "Manfred", "Thomas" ]
            - duration:
                type: static
                duration: 1
              transition:
                type: next_sensor
                index: 2
              activities:
                selection: uniform
                from:
                  type: list
                  values:
                    - [ "Hanna", "Hanno" ]
