numberOfDataSources:
  type: static
  count: 2
caseId: increasing
loadProfile:
  type: gradual
  tickCount: 100
  minimalLoad: 1
  maximalLoad: 5
dataSourceTopology:
  dataSources:
    - name: "Sensor 1"
      labels:
        sensorGroupId: "warehouse"
        location:
      sink:
        type: kafka
        bootstrapServer: "kube1-1:30376"
        topic: "process"
      duration:
        type: uniform
        lowerBound: -2
        upperBound: 4
      transition: [0.5, 0.3, 0.2]
      activities:
        selection: uniform
        from:
          type: list
          values:
            - ["Manfred", "Thomas"]
    - name: "Sensor 2"
      sink:
        type: kafka
        bootstrapServer: "kube1-1:30376"
        topic: "process2"
      duration:
        type: static
        duration: 1
      transition: [0.0, 0.8, 0.2]
      activities:
        selection: ordered
        from:
          type: list
          values:
            - [ "Manfred", "Thomas" ]
      #activities:
      #  - "A"
      #    0.5
      #  - "B"
      #    0.5
  #type: classic
  #args:
  #  dataSources:
  #    type: list
  #    ids:
  #      - "Sensor 1"
  #      - "Sensor 2"
  #      - "Sensor 3"
  #      - "Sensor 4"
  #  sink:
  #    type: ui
  #  duration:
  #    type: static
  #    duration: 10
  #  transitions:
  #    type: generateMatrix
  #    args:
  #      strategy:
  #        type: random
  #        args:
  #          numberOfTransitions:
  #            type: static
  #            count: 2
  #  activities:
  #    selection: uniform
  #    from:
  #      #type: list
  #      #values:
  #      #  - ["Manfred"]
  #      #  - ["4", "5", "6"]
  #      #  - ["7", "8", "9"]
  #      #  - ["10", "11", "12"]
  #      #  - ["13", "14", "15"]
  #      #  - ["13", "14", "15"]
  #      #  - ["16", "17", "18"]
  #      #  - ["19"]
  #      #  - ["20", "21"]
  #      #  - ["25"]
  #      #  - ["26", "27", "28"]
  #      type: distinct
  #      count:
  #        type: static
  #        count: 4
#
  #    #type: matrix
  #    #args:
  #    #  - [0.5, 0.5, 0.0, 0.0]
  #    #  - [0.5, 0.5, 0.0, 0.0]
  #    #  - [0.0, 0.5, 0.5, 0.0]
  #    #  - [0.0, 0.0, 0.5, 0.5]
  #    #  - [0.0, 0.0, 0.0, 0.5]