numberOfDataSources:
  type: static
  count: 7
caseId: increasing
loadProfile:
  type: gradual
  tickCount: 100
  minimalLoad: 1
  maximalLoad: 5
dataSourceTopology:
  dataSources:
    - name: "Receiving Goods"
      labels:
        sensorGroupId: "warehouse"
        location: ""
      sink:
        type: kafka
        bootstrapServer:
      duration:
        type: gaussian
        lowerBound: 60 # 1 hour
        upperBound: 4320 # 3 days
      transition: [0.5, 0.3, 0.2]
      activities:
        selection: uniform
        from:
          type: list
          values:
            - ["Reject", "SendImmediately", "Store"]
    - name: "Storage"
      labels:
        sensorGroupId: "warehouse"
        location: ""
      sink:
        type: console
      duration:
        type: gaussian
        lowerBound: 60 # 1 hour
        upperBound: 4320 # 3 days
      transition: [ 0.5, 0.3, 0.2 ]
      activities:
        selection: uniform
        from:
          type: list
          values:
            - [ "Store", "PassOn" ]
    - name: "Picking"
      labels:
        sensorGroupId: "warehouse"
        location: ""
      sink:
        type: console
      duration:
        type: gaussian
        lowerBound: 60 # 1 hour
        upperBound: 4320 # 3 days
      transition: [ 0.5, 0.3, 0.2 ]
      activities:
        selection: uniform
        from:
          type: list
          values:
            - [ "PickItem", "ItemDamaged", "ItemValid", "ReleaseItem" ]
    - name: "Packing"
      labels:
        sensorGroupId: "warehouse"
        location: ""
      sink:
        type: console
      duration:
        type: gaussian
        lowerBound: 60 # 1 hour
        upperBound: 4320 # 3 days
      transition: [ 0.5, 0.3, 0.2 ]
      activities:
        selection: uniform
        from:
          type: list
          values:
            - [ "BeginPack", "EndPack" ]
    - name: "Shipping"
      labels:
        sensorGroupId: "warehouse"
        location: ""
      sink:
        type: console
      duration:
        type: gaussian
        lowerBound: 60 # 1 hour
        upperBound: 4320 # 3 days
      transition: [ 0.5, 0.3, 0.2 ]
      activities:
        selection: uniform
        from:
          type: list
          values:
            - [ "LoadedToTruck" ]
    - name: "ReturnsHandling"
      labels:
        sensorGroupId: "warehouse"
        location: ""
      sink:
        type: console
      duration:
        type: gaussian
        lowerBound: 60 # 1 hour
        upperBound: 4320 # 3 days
      transition: [ 0.5, 0.3, 0.2 ]
      activities:
        selection: uniform
        from:
          type: list
          values:
            - [ "Returned" ]